# Generated by Django 4.0 on 2022-06-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='base',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shape',
            name='side1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shape',
            name='side2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shape',
            name='side3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shape',
            name='side4',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
