# Generated by Django 4.0 on 2022-06-02 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_shape_base_shape_height_alter_shape_side1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shape',
            name='height',
        ),
        migrations.RemoveField(
            model_name='shape',
            name='side4',
        ),
    ]
