# Generated by Django 4.0 on 2022-06-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_shape_height_remove_shape_side4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shape',
            name='base',
        ),
    ]
