# Generated by Django 4.0 on 2022-06-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_shape_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='perimeter',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
